### PR TITLE
Addition of Uri property to CalendarEvent class

### PR DESCRIPTION
**Pull request by Yogeshk25**
This PR adds a new property Uri to CalendarEvent class.
With this change for android, minimum API level changes to 16 from 15. (refer this [https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns.html#CUSTOM_APP_URI](https://developer.android.com/reference/android/provider/CalendarContract.EventsColumns.html#CUSTOM_APP_URI))

This field can help for creating deep linking, to launch app from system calendar.

### CODE REVIEW

**Comment by TheAlmightyBob** [comment]
Interesting...

Are you successfully using this property? On all three platforms?

It seems somewhat platform-specific... e.g., on iOS it's a user-editable URL that can just open up a web page, whereas the Android property seems specifically for linking to custom apps.

And even if you were just using it for linking to custom apps, it seems like you would need to populate it with different data depending on the platform? Or is the same value able to successfully launch your app on each platform?

**Comment by Yogeshk25** [comment]
Yes indeed. This property is platform specific., I am using this new property on all three platform.

Yes this field contains different value on different platforms. It's upto user to pass correct value to this field for being able to use it efficiently.

**Comment by TheAlmightyBob** [comment]
If you need to pass different values on different platforms, then what is the value of exposing it in a cross-platform abstraction? Are you using this from platform-specific code? Do you have "if Android"-style branching in shared code? Are you passing the value down from platform code into portable code? Just trying to understand the use case here...

**Comment by Yogeshk25** [comment]
No there are no "if Android" -style branching in shared code.
platform specific codes are in platform specific project, just like already existing properties of CalendarEvent class.

One use case is launching an app from system calendar app.
if an application supports deep linking and listening for a uri something like myapp://userdetail?uid=12
then this field can be used to store this URI, when a user clicks on this uri from there system calendar, they will be redirected to a specific page of that application.

**Comment by TheAlmightyBob** [comment]
Sorry, I meant where are you _setting_ the URI property from? You said "platform specific codes are in platform specific project, just like already existing properties of CalendarEvent class," but CalendarEvent is a cross-platform PCL abstraction, with the existing properties intended to be used from portable code. But if the value you put into the URI property has to be platform-specific, I'm curious how useful it is to expose it to portable code.

I can't help wondering if it would cause confusion to combine these slightly-different platform-specific properties into a single property of CalendarEvent. Seems like it could encourage writing code that won't work (e.g., trying to use the same app URI on every platform... or maybe you just wanted to link to a web page, which would be fine on iOS but may be a problem on Android?).

If you are only setting URI from platform-specific code, then maybe there's a general use case for being able to access additional platform-specific properties from platform code? (so, e.g., on Android you would actually set "custom_app_uri", on iOS "url", etc)

Possibly documenting the property you added would be enough, but I wanted to understand if it's actually necessary to have this as a property on CalendarEvent or if it's worth exploring other ways of doing this...

**Comment by trevoriancox** [comment]
This sounds like a very important feature for the component. Any app that uses the Calendar component to create a calendar will likely want that calendar's event description and/or link to reference the app that the event came from. We can deal with the cross-platform issues.

**Pull request closed without merging**
