### PR TITLE
Added NSCalendarsUsageDescription to the info.plist to allow the test…

### PR DESCRIPTION
**Pull request by bmacombe**
updated test project to run correctly on iOS 10.0

### CODE REVIEW

**Comment by bmacombe** [comment]
They aren't, I'll I'll try again not including them.  First time really using Git, I'm used to Team System :)

**Comment by bmacombe** [comment]
I think I have just the plist files for both iOS test projects updated now.  Starting to get the hang of git :)

**Comment by TheAlmightyBob** [comment]
If you could rebase off the latest master, it should resolve the Appveyor failure and file conflict.
It would also be good to squash those commits into one (via interactive rebase).

But, frankly, if you're new to git, and since this is a small change, you might find it easier to start over and try again... pull the latest master, new branch off that, make the change again, create a fresh pull request. It's up to you, though.

(P.S. the reason for the Appveyor failure and file conflict is that Xamarin no longer supports the non-Unified iOS configuration, so it has been removed)

**Comment by bmacombe** [comment]
Thanks for the tips, I'll try it again here soon.  It's worth the effort just to get some experience.

**Pull request closed without merging**
