### PR TITLE
Fixing uwp

### PR DESCRIPTION
**Pull request by jphellemons**
New day, new try. Tried to rebase from a new created branch. But still no auto merge available. Hope that this will work. Could you please merge it? I have added a repository tag in the nuspec.
It's not yet listed on https://docs.microsoft.com/en-us/nuget/reference/nuspec
But it's in the demo of the build 2018 .net roadmap 
https://www.youtube.com/watch?v=KAIJ3ezQb3c&feature=youtu.be&t=52m
And it will allow people to debug the source of the nuget package.

### CODE REVIEW

**Comment by jphellemons** [comment]
Build failed "The 'branch' attribute is not declared." while there is a branch attribute on line 46 of the nuspec.

**Comment by TheAlmightyBob** [comment]
I'm not sure what kind of rebasing you're doing but there are still commits that shouldn't be here. My best guess is that you rebased your new branch on top of your already-modified `master` branch in your fork rather than the real `master` branch?

**Comment by jphellemons** [comment]
Yes, sorry for messing up the pr's with rebasing etc. I am currently setting up an AppVeyor on my fork. To see if I can speed things up. There is a checkbox in AppVeyor to overwrite the assemblyinfo. But the assemblyinfo of the android and ios project contains 0.6 as version and the uwp has 1.0 since the error was about 1.0, I thought that it might be the case that AppVeyor does auto increment the nuget buildnr but not the internal assemblies. That is why I was trying it with the placeholders in the several assemblyinfo.cs files.

**Comment by TheAlmightyBob** [comment]
> the uwp has 1.0 since the error was about 1.0

Actually I think you're on the right track but just slightly off. The error wasn't that UWP _has_ 1.0, it's that it _couldn't find_ 1.0. Which is because it has 0.6.

What has 1.0 are the .netstandard assemblies. Which is because .netstandard controls assembly versioning differently. Which finally explains why this broke when switching to .netstandard.

I found that AppVeyor now has a new separate configuration property for ".NET Core .csproj patching". This was previously disabled but I just turned it on. Unfortunately I can't test it because of the aforementioned Android build failure in AppVeyor. But I strongly suspect that this is the problem.

(and thanks, I wouldn't have thought to look at the assembly versions if you hadn't started down this path)


[Btw, if it's not clear why the .netstandard assemblies being 1.0 would lead to this error, it's because of the "bait and switch" technique that is used for Xamarin plugins. Your app's portable core project needs to be able to reference a similarly portable version of Plugin.Calendars.dll, hence the .netstandard library. So it is compiled against that assembly rather than the UWP assembly, and then at the last second the UWP version is swapped in its place (hence "bait and switch") so that you can actually call platform-specific logic from your portable code. So what would be happening here is that your project was compiled against a 1.0 assembly and then run with a 0.6 assembly so it complains that it can't find the 1.0 assembly that it was expecting.]

**Comment by jphellemons** [comment]
Btw I am currently 23 minutes waiting for AppVeyor to install the Android SDK. I used this powershell script from their help forum. I do not know how you enabled the android sdk in the build process?
https://help.appveyor.com/discussions/problems/3551-xamarinandroid-android-sdk-api-level-15-missing
appveyor-android

**Comment by TheAlmightyBob** [comment]
@jphellemons I also use a powershell script, which you can find in the `CI` subfolder of the project. You're using an older version of the script (mine used to look like that years ago).

**Comment by TheAlmightyBob** [comment]
It looks like the powershell script needs to be updated again. I don't have time to dig further into it right now, but I see where it's failing:
```
Accept? (y/N): Skipping following packages as the license is not accepted:
Android SDK Platform 15
The following packages can not be installed since their licenses or those of the packages they depend on were not accepted:
  platforms;android-15
```

The powershell script attempts to accept the license by using `echo 'y' | ....update sdk command....`, but previously in the output there's:
```
"android" SDK commands can be translated to sdkmanager commands on a best-effort basis.
(This prompt can be suppressed with the --use-sdk-wrapper commend-line argument
or by setting the USE_SDK_WRAPPER environment variable)
Continue? [y/N]: 
```
So the `echo 'y'` must be going to that "Continue" prompt (which I guess is new) instead of to the license acceptance prompt...

**Comment by TheAlmightyBob** [comment]
Okay I just merged a change to fix the Android CI (as I was writing that last message I noticed the line, `This prompt can be suppressed with the --use-sdk-wrapper commend-line argument` so figured I should try that)

(also, "commend-line"?? Wow Google, can't be bothered to spellcheck your messages, eh?)

**Comment by TheAlmightyBob** [comment]
Okay, the versions are still 1.0 though, so there must be more required (I'm guessing csproj changes) for that AppVeyor feature to take effect

**Pull request closed without merging**
